name: CI

on:
  push:

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@main

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@main

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@main
    with:
      upload-artifact: true
      artifact-name: package
      dist-folder: dist
      retention-days: 3
      build-command: build
