name: CI

on:
  push:

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v1.0.0

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v1.0.0

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v1.0.0
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v1.0.0
    with:
      upload-artifact: true
      artifact-name: package
      dist-folder: dist
      retention-days: 3
      build-command: build

  publish:
    needs: [lint, test, security, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access=public
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
