name: CI

on:
  push:

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v3.5.0
    with:
      node-version: 20.x

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v3.5.0
    with:
      node-version: 20.x

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v3.5.0
    with:
      args: --all-projects
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v3.5.0
    with:
      node-version: 20.x
      upload_artifact: true
      build_folder: package
      build_folder_path: dist
      retention_days: 3
      build_command: build
      
