name: NPM Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: dvsa/.github/.github/workflows/nodejs-publish.yaml@v2.1
    with:
      node_version: '16.x'
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}