name: NPM Publish

on:
  push:

jobs:
  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v2.3

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v2.3
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v2.3
    with:
      upload_artifact: true
      build_folder: package
      build_folder_path: dist
      retention_days: 3
      build_command: build

  publish:
    needs: [test, security, build]
    uses: dvsa/.github/.github/workflows/nodejs-publish.yaml@v2.3
    with:
      node_version: '16.x'
      download_artifact: true
      build_folder: package
      build_folder_path: dist
      args: "--dry-run"
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}