name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node


  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v4.0.1
    with:
      node-version: '20.x'

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v4.0.1
    with:
      args: --all-projects
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v4.0.1
    if: ${{ needs.release-please.outputs.release_created }}
    needs: [ release-please, test, security ]
    with:
      node-version: '20.x'
      upload-artifact: true
      build-folder: package
      build-folder-path: dist
      retention-days: 3
      build-command: npm run build

  publish:
    needs: [release-please, test, security, build]
    if: ${{ needs.release-please.outputs.release_created }}
    uses: dvsa/.github/.github/workflows/nodejs-publish.yaml@v4.0.1
    with:
      node-version: '20.x'
      download-artifact: true
      build-folder: package
      build-folder-path: dist
      args: "--access=public"
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
